In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import datetime

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.metrics import confusion_matrix, classification_report

In [11]:
train_file = './archive/model_2016_ST4000DM000.csv'
test_file = './archive/model_2017_ST4000DM000.csv'

In [18]:
df = pd.read_csv(train_file)
df_t = pd.read_csv(test_file)

In [15]:
df

,date,serial_number,model,capacity_bytes,failure,smart_1_normalized,smart_1_raw,smart_2_normalized,smart_2_raw,smart_3_normalized,...,smart_250_normalized,smart_250_raw,smart_251_normalized,smart_251_raw,smart_252_normalized,smart_252_raw,smart_254_normalized,smart_254_raw,smart_255_normalized,smart_255_raw
0,2016-01-01,W300K1XB,ST4000DM000,4000787030016,0,119.0,233526840.0,NaN,NaN,92.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-01-01,Z300H1WJ,ST4000DM000,4000787030016,0,117.0,163372664.0,NaN,NaN,91.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-01-01,Z304JL7B,ST4000DM000,4000787030016,0,108.0,17223464.0,NaN,NaN,96.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-01-01,Z302BVHP,ST4000DM000,4000787030016,0,116.0,112452648.0,NaN,NaN,92.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-01-01,S300Z5BS,ST4000DM000,4000787030016,0,119.0,218952312.0,NaN,NaN,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1076066,2016-09-30,Z30412ZR,ST4000DM000,4000787030016,0,116.0,101943384.0,NaN,NaN,91.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1076067,2016-09-30,W300D55C,ST4000DM000,4000787030016,1,119.0,232389536.0,NaN,NaN,91.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1076068,2016-09-30,Z3011F9X,ST4000DM000,4000787030016,0,115.0,92757144.0,NaN,NaN,91.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1076069,2016-09-30,Z304HV1N,ST4000DM000,4000787030016,0,112.0,44067728.0,NaN,NaN,94.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1076070,2016-09-30,S300XCF3,ST4000DM000,4000787030016,0,114.0,75153288.0,NaN,NaN,97.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1076071 entries, 0 to 1076070
Data columns (total 95 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   date                  1076071 non-null  object
 1   serial_number         1076071 non-null  object
 2   model                 1076071 non-null  object
 3   capacity_bytes        1076071 non-null  int64
 4   failure               1076071 non-null  int64
 5   smart_1_normalized    1076069 non-null  float64
 6   smart_1_raw           1076069 non-null  float64
 7   smart_2_normalized    0 non-null        float64
 8   smart_2_raw           0 non-null        float64
 9   smart_3_normalized    1076069 non-null  float64
 10  smart_3_raw           1076069 non-null  float64
 11  smart_4_normalized    1076069 non-null  float64
 12  smart_4_raw           1076069 non-null  float64
 13  smart_5_normalized    1076069 non-null  float64
 14  smart_5_raw           1076069 non-null  float64
 15  smart_7_normalized    1076069 non-null  float64
 16  smart_7_raw           1076069 non-null  float64
 17  smart_8_normalized    0 non-null        float64
 18  smart_8_raw           0 non-null        float64
 19  smart_9_normalized    1076069 non-null  float64
 20  smart_9_raw           1076069 non-null  float64
 21  smart_10_normalized   1076069 non-null  float64
 22  smart_10_raw          1076069 non-null  float64
 23  smart_11_normalized   0 non-null        float64
 24  smart_11_raw          0 non-null        float64
 25  smart_12_normalized   1076069 non-null  float64
 26  smart_12_raw          1076069 non-null  float64
 27  smart_13_normalized   0 non-null        float64
 28  smart_13_raw          0 non-null        float64
 29  smart_15_normalized   0 non-null        float64
 30  smart_15_raw          0 non-null        float64
 31  smart_22_normalized   0 non-null        float64
 32  smart_22_raw          0 non-null        float64
 33  smart_183_normalized  1076069 non-null  float64
 34  smart_183_raw         1076069 non-null  float64
 35  smart_184_normalized  1076069 non-null  float64
 36  smart_184_raw         1076069 non-null  float64
 37  smart_187_normalized  1076069 non-null  float64
 38  smart_187_raw         1076069 non-null  float64
 39  smart_188_normalized  1076069 non-null  float64
 40  smart_188_raw         1076069 non-null  float64
 41  smart_189_normalized  1076069 non-null  float64
 42  smart_189_raw         1076069 non-null  float64
 43  smart_190_normalized  1076069 non-null  float64
 44  smart_190_raw         1076069 non-null  float64
 45  smart_191_normalized  1076069 non-null  float64
 46  smart_191_raw         1076069 non-null  float64
 47  smart_192_normalized  1076069 non-null  float64
 48  smart_192_raw         1076069 non-null  float64
 49  smart_193_normalized  1076069 non-null  float64
 50  smart_193_raw         1076069 non-null  float64
 51  smart_194_normalized  1076069 non-null  float64
 52  smart_194_raw         1076069 non-null  float64
 53  smart_195_normalized  0 non-null        float64
 54  smart_195_raw         0 non-null        float64
 55  smart_196_normalized  0 non-null        float64
 56  smart_196_raw         0 non-null        float64
 57  smart_197_normalized  1076069 non-null  float64
 58  smart_197_raw         1076069 non-null  float64
 59  smart_198_normalized  1076069 non-null  float64
 60  smart_198_raw         1076069 non-null  float64
 61  smart_199_normalized  1076069 non-null  float64
 62  smart_199_raw         1076069 non-null  float64
 63  smart_200_normalized  0 non-null        float64
 64  smart_200_raw         0 non-null        float64
 65  smart_201_normalized  0 non-null        float64
 66  smart_201_raw         0 non-null        float64
 67  smart_220_normalized  0 non-null        float64
 68  smart_220_raw         0 non-null        float64
 69  smart_222_normalized  0 non-null        float64
 70  smart_222_raw         0 non-null        float64
 71  smart_223_normalized  0 non-null        float64
 72  smart_223_raw         0 non-null        float64
 73  smart_224_normalized  0 non-null        float64
 74  smart_224_raw         0 non-null        float64
 75  smart_225_normalized  0 non-null        float64
 76  smart_225_raw         0 non-null        float64
 77  smart_226_normalized  0 non-null        float64
 78  smart_226_raw         0 non-null        float64
 79  smart_240_normalized  1076069 non-null  float64
 80  smart_240_raw         1076069 non-null  float64
 81  smart_241_normalized  1076069 non-null  float64
 82  smart_241_raw         1076069 non-null  float64
 83  smart_242_normalized  1076069 non-null  float64
 84  smart_242_raw         1076069 non-null  float64
 85  smart_250_normalized  0 non-null        float64
 86  smart_250_raw         0 non-null        float64
 87  smart_251_normalized  0 non-null        float64
 88  smart_251_raw         0 non-null        float64
 89  smart_252_normalized  0 non-null        float64
 90  smart_252_raw         0 non-null        float64
 91  smart_254_normalized  0 non-null        float64
 92  smart_254_raw         0 non-null        float64
 93  smart_255_normalized  0 non-null        float64
 94  smart_255_raw         0 non-null        float64
dtypes: float64(90), int64(2), object(3)
memory usage: 779.9+ MB

In [19]:
df = df.dropna(axis=1, how='all')
df = df.dropna(axis=0, how='any')
df

,date,serial_number,model,capacity_bytes,failure,smart_1_normalized,smart_1_raw,smart_3_normalized,smart_3_raw,smart_4_normalized,...,smart_198_normalized,smart_198_raw,smart_199_normalized,smart_199_raw,smart_240_normalized,smart_240_raw,smart_241_normalized,smart_241_raw,smart_242_normalized,smart_242_raw
0,2016-01-01,W300K1XB,ST4000DM000,4000787030016,0,119.0,233526840.0,92.0,0.0,100.0,...,100.0,0.0,200.0,0.0,100.0,16793.0,100.0,2.186669e+10,100.0,2.070964e+11
1,2016-01-01,Z300H1WJ,ST4000DM000,4000787030016,0,117.0,163372664.0,91.0,0.0,100.0,...,100.0,0.0,200.0,0.0,100.0,18300.0,100.0,1.970806e+10,100.0,9.107464e+10
2,2016-01-01,Z304JL7B,ST4000DM000,4000787030016,0,108.0,17223464.0,96.0,0.0,100.0,...,100.0,0.0,200.0,0.0,100.0,1972.0,100.0,1.496244e+10,100.0,1.210172e+09
3,2016-01-01,Z302BVHP,ST4000DM000,4000787030016,0,116.0,112452648.0,92.0,0.0,100.0,...,100.0,0.0,200.0,0.0,100.0,3671.0,100.0,1.794955e+10,100.0,1.594817e+09
4,2016-01-01,S300Z5BS,ST4000DM000,4000787030016,0,119.0,218952312.0,99.0,0.0,100.0,...,100.0,0.0,200.0,0.0,100.0,5380.0,100.0,2.452976e+10,100.0,1.177120e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1076066,2016-09-30,Z30412ZR,ST4000DM000,4000787030016,0,116.0,101943384.0,91.0,0.0,100.0,...,100.0,0.0,200.0,40.0,100.0,8849.0,100.0,1.625594e+10,100.0,1.321693e+11
1076067,2016-09-30,W300D55C,ST4000DM000,4000787030016,1,119.0,232389536.0,91.0,0.0,100.0,...,100.0,0.0,200.0,0.0,100.0,28663.0,100.0,2.814145e+10,100.0,1.539055e+11
1076068,2016-09-30,Z3011F9X,ST4000DM000,4000787030016,0,115.0,92757144.0,91.0,0.0,100.0,...,100.0,0.0,200.0,0.0,100.0,20726.0,100.0,2.592566e+10,100.0,1.699410e+11
1076069,2016-09-30,Z304HV1N,ST4000DM000,4000787030016,0,112.0,44067728.0,94.0,0.0,100.0,...,100.0,0.0,200.0,0.0,100.0,6923.0,100.0,2.294564e+10,100.0,3.441859e+09
1076070,2016-09-30,S300XCF3,ST4000DM000,4000787030016,0,114.0,75153288.0,97.0,0.0,100.0,...,100.0,0.0,200.0,0.0,100.0,10027.0,100.0,3.204931e+10,100.0,6.534987e+09

In [20]:
df = df.loc[:, df.apply(lambda col: col.max() != col.min())]
df

,date,serial_number,failure,smart_1_normalized,smart_1_raw,smart_3_normalized,smart_4_normalized,smart_4_raw,smart_5_normalized,smart_5_raw,...,smart_194_normalized,smart_194_raw,smart_197_normalized,smart_197_raw,smart_198_normalized,smart_198_raw,smart_199_raw,smart_240_raw,smart_241_raw,smart_242_raw
0,2016-01-01,W300K1XB,0,119.0,233526840.0,92.0,100.0,11.0,100.0,0.0,...,34.0,34.0,100.0,0.0,100.0,0.0,0.0,16793.0,2.186669e+10,2.070964e+11
1,2016-01-01,Z300H1WJ,0,117.0,163372664.0,91.0,100.0,15.0,100.0,0.0,...,29.0,29.0,100.0,0.0,100.0,0.0,0.0,18300.0,1.970806e+10,9.107464e+10
2,2016-01-01,Z304JL7B,0,108.0,17223464.0,96.0,100.0,4.0,100.0,0.0,...,31.0,31.0,100.0,0.0,100.0,0.0,0.0,1972.0,1.496244e+10,1.210172e+09
3,2016-01-01,Z302BVHP,0,116.0,112452648.0,92.0,100.0,19.0,100.0,0.0,...,30.0,30.0,100.0,0.0,100.0,0.0,0.0,3671.0,1.794955e+10,1.594817e+09
4,2016-01-01,S300Z5BS,0,119.0,218952312.0,99.0,100.0,1.0,100.0,0.0,...,23.0,23.0,100.0,0.0,100.0,0.0,0.0,5380.0,2.452976e+10,1.177120e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1076066,2016-09-30,Z30412ZR,0,116.0,101943384.0,91.0,100.0,19.0,100.0,0.0,...,25.0,25.0,100.0,0.0,100.0,0.0,40.0,8849.0,1.625594e+10,1.321693e+11
1076067,2016-09-30,W300D55C,1,119.0,232389536.0,91.0,100.0,21.0,100.0,0.0,...,27.0,27.0,100.0,0.0,100.0,0.0,0.0,28663.0,2.814145e+10,1.539055e+11
1076068,2016-09-30,Z3011F9X,0,115.0,92757144.0,91.0,100.0,17.0,100.0,0.0,...,27.0,27.0,100.0,0.0,100.0,0.0,0.0,20726.0,2.592566e+10,1.699410e+11
1076069,2016-09-30,Z304HV1N,0,112.0,44067728.0,94.0,100.0,6.0,100.0,0.0,...,20.0,20.0,100.0,0.0,100.0,0.0,0.0,6923.0,2.294564e+10,3.441859e+09
1076070,2016-09-30,S300XCF3,0,114.0,75153288.0,97.0,100.0,5.0,100.0,0.0,...,22.0,22.0,100.0,0.0,100.0,0.0,0.0,10027.0,3.204931e+10,6.534987e+09

In [21]:
df_failed = df[df['failure']==1]
df_normal = df[df['failure']==0]
print(len(df_failed))
print(len(df_normal))

62707
1013362

In [29]:
df_t = df_t.dropna(axis=1, how='all')
df_t = df_t.dropna(axis=0, how='any')
df_t = df_t.loc[:, df_t.apply(lambda col: col.max() != col.min())]
df_t

,date,serial_number,failure,smart_1_normalized,smart_1_raw,smart_3_normalized,smart_4_normalized,smart_4_raw,smart_5_normalized,smart_5_raw,...,smart_194_normalized,smart_194_raw,smart_197_normalized,smart_197_raw,smart_198_normalized,smart_198_raw,smart_199_raw,smart_240_raw,smart_241_raw,smart_242_raw
0,2017-10-01,Z301CEB2,1,120.0,241804680.0,91.0,100.0,17.0,100.0,0.0,...,25.0,25.0,100.0,0.0,100.0,0.0,0.0,18477.0,1.783750e+10,1.249269e+11
1,2017-10-01,S3010M7H,0,108.0,17249088.0,91.0,100.0,15.0,100.0,0.0,...,26.0,26.0,100.0,0.0,100.0,0.0,0.0,19722.0,3.443496e+10,5.434673e+10
2,2017-10-01,Z300CWTK,0,120.0,234934408.0,91.0,100.0,11.0,100.0,0.0,...,18.0,18.0,100.0,0.0,100.0,0.0,0.0,35420.0,2.979836e+10,1.672180e+11
3,2017-10-01,Z304HQR4,0,112.0,48440152.0,97.0,100.0,3.0,100.0,0.0,...,21.0,21.0,100.0,0.0,100.0,0.0,0.0,16560.0,3.833137e+10,3.896329e+10
4,2017-10-01,Z304SY3R,0,117.0,146163016.0,92.0,100.0,11.0,100.0,0.0,...,23.0,23.0,100.0,0.0,100.0,0.0,0.0,15482.0,3.703801e+10,4.022098e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178293,2017-12-31,Z304JGA7,0,117.0,118145352.0,91.0,100.0,9.0,100.0,0.0,...,22.0,22.0,100.0,0.0,100.0,0.0,0.0,18560.0,4.269857e+10,6.796492e+10
178294,2017-12-31,Z305JWYT,0,114.0,58727264.0,97.0,100.0,3.0,100.0,0.0,...,24.0,24.0,100.0,0.0,100.0,0.0,0.0,15728.0,3.431348e+10,7.769699e+10
178295,2017-12-31,Z3025CF3,0,118.0,190472976.0,92.0,100.0,23.0,100.0,0.0,...,26.0,26.0,100.0,0.0,100.0,0.0,0.0,24492.0,2.330789e+10,2.107242e+11
178296,2017-12-31,Z3015JBZ,0,111.0,36657712.0,93.0,100.0,7.0,100.0,0.0,...,23.0,23.0,100.0,0.0,100.0,0.0,0.0,26396.0,2.201618e+10,1.722478e+11
178297,2017-12-31,S300Z7GS,0,115.0,89171176.0,96.0,100.0,4.0,100.0,0.0,...,24.0,24.0,100.0,0.0,100.0,0.0,0.0,22897.0,4.702349e+10,5.911582e+10

In [24]:
df_train_target = df['failure']
df_test_target = df_t['failure']
df_train = df.drop(columns=['date','serial_number','failure'])
df_test = df_t.drop(columns=['date','serial_number','failure'])

In [26]:
lda = LinearDiscriminantAnalysis()
lda.fit(df_train,df_train_target)
y_pred = lda.predict(df_test)
print(cofusion_matrix(df_test_target, y_pred))
print(classification_report(df_test_target, y_pred, target_names=['normal','failed']))

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- capacity_bytes
- model
- smart_10_normalized
- smart_10_raw
- smart_11_normalized
- ...

In [ ]:
from sk